version: "3.8"

services:
  
  frontend: 
    build: ./frontend 
    ports: 
      - "3000:3000" 
    container_name: frontend-docker
    restart: always 
 

  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - EXTERNAL_PORT=3001
      - PGUSER=root
      - PGPASSWORD=root
      - PGDATABASE=jobly
      - PGHOST=postgres
    container_name: backend-docker
    restart: always
    networks: 
      - backend
    volumes:
      - ./docker-seed/docker-seed.sql:/docker-entrypoint-initdb.d/docker-seed.sql
 
  postgres:
    build: ./docker-db
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root 
      - POSTGRES_DB=jobly
    container_name: postgres-docker
    volumes:
      - jobly-data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role===manager"

networks:
  backend:

volumes:
  jobly-data:
  docker-seed: